global:
  scrape_interval: 30s # Set the scrape interval to every 30 seconds.
  evaluation_interval: 30s # Evaluate rules every 30 seconds.

scrape_configs:
  - job_name: "celes_das"
    static_configs:
      - targets: [ "otel-collector:8889" ]
